#!/bin/sh
set -e

NAME=$(gum input --placeholder "Name")
URL=$(gum input --placeholder "Website URL")
URL=${URL:-"No Web"}
CUISINE=$(gum input --placeholder "Cuisine type")
CUISINE=${CUISINE:-"Unknown"}
RATING=$(gum input --placeholder "Rating (1-3)")
RATING=${RATING:-"0"}
COST=$(gum input --placeholder "Cost (1-3)")
COST=${COST:-"0"}

# Get the next restaurant number
NEXT_NUM=$(tail -1 restaurants.txt | cut -d'.' -f1 | awk '{print $1 + 1}')

# Add new restaurant to file
echo "$NEXT_NUM. $NAME # $URL # $CUISINE # $RATING # $COST" >> restaurants.txt

echo "Added restaurant: $NAME"
