#!/bin/sh
read -r -d '' PROMPT <<EOF
Ordena la lista de restaurantes alfabeticamente.
No debe haber espacios en blanco al final de cada linea en la nueva lista.
Ignora la primera linea, es la cabecera de tabla, pero aniadela a la lista final.
No respondas con texto adicional.
Re-numera las lineas si es necesario.
Asegurate que no falta ningun restaurante en la nueva lista.
EOF

cat restaurants.txt | gh models run openai/gpt-4.1 "$PROMPT" > restaurants.txt.new
mv restaurants.txt.new restaurants.txt
cp restaurants.txt docs/
